name: Run Tests

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Ruby & Ceedling
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby
          gem install --user-install ceedling
          echo "$(ruby -r rubygems -e 'puts Gem.user_dir')/bin" >> $GITHUB_PATH

      - name: Run wireless station firmware tests
        working-directory: wireless_station_firmware/tests
        run: ceedling test:all
